# Generated by Django 5.1.5 on 2025-01-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload an image for the music', null=True, upload_to='music_covers/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(help_text='Upload MP3 or ZIP files', upload_to='music_files/'),
        ),
    ]
