# Generated by Django 5.1.5 on 2025-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_music_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Upload a ZIP file containing MP3s', null=True, upload_to='album_zips/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(help_text='Upload MP3 files', upload_to='music_files/'),
        ),
    ]
