# Generated by Django 5.1.5 on 2025-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_zip_file_alter_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload an image for the track', null=True, upload_to='music_covers/'),
        ),
    ]
