# Generated by Django 5.1.5 on 2025-01-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_category_album_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_ad', models.TextField(blank=True, help_text='AdSense code for Header', null=True)),
                ('footer_ad', models.TextField(blank=True, help_text='AdSense code for Footer', null=True)),
                ('between_tracks_ad', models.TextField(blank=True, help_text='AdSense code between tracks', null=True)),
            ],
            options={
                'verbose_name': 'AdSense Setting',
                'verbose_name_plural': 'AdSense Settings',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a category image', null=True, upload_to='category_images/'),
        ),
    ]
