# Generated by Django 5.1.5 on 2025-01-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_adsettings_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsettings',
            name='between_tracks_ad',
            field=models.TextField(blank=True, help_text='AdSense code between album tracks', null=True),
        ),
    ]
